name: EECS 440 Linter

on: push

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  lint-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - run: curl -LJOo ${GITHUB_WORKSPACE}/clang-format-440 https://github.com/sqd/eecs440-format/releases/download/v0.0.1/clang-format-440
      - run: chmod u+x ${GITHUB_WORKSPACE}/clang-format-440
      - uses: actions/checkout@v2
      - run: ls -la
      - run: ${GITHUB_WORKSPACE}/clang-format-440 --help
      # - run: find . -path ./.git -prune -false -o -iname *.h -o -iname *.cpp 2>/dev/null | xargs ./clang-format-440 --style=EECS440 --dry-run --Werror
      - run: find ${GITHUB_WORKSPACE}/src -iname "*.h" -o -iname "*.cpp" 2>/dev/null | xargs ${GITHUB_WORKSPACE}/clang-format-440 --style=EECS440 --dry-run --Werror