name: EECS 440 Linter

on: push

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  lint-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -LJOo clang-format-440 https://github.com/sqd/eecs440-format/releases/download/v0.0.1/clang-format-440
      - run: chmod u+x clang-format-440
      - run: find . -path ./.git -prune -false -o -iname "*.h" -o -iname "*.cpp" | xargs ./clang-format-440 --style=EECS440 --dry-run --Werror